.Dd $Mdocdate$
.Dt TEST 1
.Os
.Sh NAME
.Nm test
.Nd do something
.Sh DESCRIPTION
.Pp
Paragraph with \fIitalic text\fP.
.Pp
Another para.
.Ss Subsection
.Pp
Subsection text.
.Ss A list:
.Bl -bullet
.It
item
.Bl -dash -compact
.It
item2
.It
item2
.Bl -bullet -compact
.It
item3
.El
.El
.It
item
.It
Bullet with
.Pp
Some text embedded inside it.
.El
.Pp
A paragraph using =begin para.
.Pp
Which can include more text.
.Bl -bullet
.It
and embedded bullet points

